steps:
  - action: loop_forever
    steps:
      - action: loop_until_found
        exit_if: 'target'

        steps:
          - action: search_template
            screenshot_type: 'around_mouse'
            radius: 300
            template_path: 'template/img.png'
            threshold: 0.9
            save_as: 'target'

      - action: mouse_action
        action_type: 'mouse_down_or_up'
        pressing_type: 'down'
        time_of_movement: 1
        point_from: 'target'

      - action: mouse_action
        action_type: 'move_to'
        time_of_movement: 1
        coordinates: [ 100, 200 ]
        point_from: 'target'

      - action: mouse_action
        action_type: 'mouse_down_or_up'
        pressing_type: 'up'
        time_of_movement: 1
        point_from: 'target'

      - action: loop_until_found
        exit_if: 'target'

        steps:
          - action: search_template
            screenshot_type: 'around_mouse'
            radius: 300
            template_path: 'template/img_1.png'
            threshold: 0.9
            save_as: 'target'

      - action: mouse_action
        action_type: 'move_to'
        pressing_type: ''
        point_from: 'target'
