steps:
#  - action: loop_forever
#    steps:
  - action: loop_until_found
    exit_if: 'target'

    steps:
      - action: search_template
        screenshot_type: 'full'
        radius: 300
        template_path: 'template/img.png'
        threshold: 0.9
        save_as: 'target'

  - action: mouse_action
    action_type: 'move_to_and_click'
    pressing_type: 'double_click'
    time_of_movement: 1
    point_from: 'target'

  - action: loop_until_found
    exit_if: 'target'

    steps:
      - action: search_template
        screenshot_type: 'full'
#        radius: 300
        template_path: 'template/img_3.png'
        threshold: 0.8
        save_as: 'target'

  - action: mouse_action
    action_type: 'move_to_and_click'
    pressing_type: 'click'
    time_of_movement: 1
    point_from: 'target'

  - action: keyboard_action
    path: 'template/explanation.txt'
    action_type: 'print_text'
    interval: 0.02
